# Generated by Django 4.2.20 on 2025-12-21 08:25

from django.db import migrations, models


def migrate_to_global_categories(apps, schema_editor):
    """
    Migrate from user-specific categories to global categories
    """
    Category = apps.get_model('ledger', 'Category')
    Subcategory = apps.get_model('ledger', 'Subcategory')
    Expense = apps.get_model('ledger', 'Expense')
    
    # Default categories and subcategories data
    DEFAULT_CATEGORIES = {
        'Food & Dining': [
            'Groceries',
            'Restaurants',
            'Fast Food',
            'Coffee Shops',
            'Delivery',
        ],
        'Transportation': [
            'Fuel',
            'Public Transport',
            'Taxi/Rideshare',
            'Parking',
            'Car Maintenance',
            'Car Insurance',
        ],
        'Housing': [
            'Rent',
            'Mortgage',
            'Utilities',
            'Internet',
            'Home Insurance',
            'Repairs & Maintenance',
        ],
        'Health & Fitness': [
            'Doctor Visits',
            'Pharmacy',
            'Gym Membership',
            'Sports Equipment',
            'Health Insurance',
        ],
        'Entertainment': [
            'Movies',
            'Games',
            'Streaming Services',
            'Concerts',
            'Hobbies',
        ],
        'Shopping': [
            'Clothing',
            'Electronics',
            'Home Goods',
            'Books',
            'Personal Care',
        ],
        'Education': [
            'Tuition',
            'Books',
            'Online Courses',
            'School Supplies',
        ],
        'Travel': [
            'Flights',
            'Hotels',
            'Vacation',
            'Travel Insurance',
        ],
        'Bills & Utilities': [
            'Electricity',
            'Water',
            'Gas',
            'Phone',
            'Internet',
        ],
        'Personal Care': [
            'Haircut',
            'Cosmetics',
            'Clothing',
            'Toiletries',
        ],
        'Insurance': [
            'Health Insurance',
            'Car Insurance',
            'Home Insurance',
            'Life Insurance',
        ],
        'Savings & Investments': [
            'Emergency Fund',
            'Retirement',
            'Investments',
        ],
        'Gifts & Donations': [
            'Gifts',
            'Charity',
            'Donations',
        ],
        'Other': [
            'Miscellaneous',
            'Unexpected Expenses',
        ],
    }
    
    # Create global categories and subcategories
    category_mapping = {}  # category_name -> global_category
    subcategory_mapping = {}  # (category_name, subcategory_name) -> global_subcategory
    
    for main_category_name, subcategories in DEFAULT_CATEGORIES.items():
        # Find existing category with this name (from any user)
        existing_category = Category.objects.filter(name__iexact=main_category_name).first()
        if existing_category:
            # Use existing category
            main_category = existing_category
        else:
            # Create new global category - we need to pick a user temporarily
            # Use the first user we find
            first_user = apps.get_model('auth', 'User').objects.first()
            if not first_user:
                continue  # Skip if no users exist
            main_category = Category.objects.create(
                name=main_category_name,
                user=first_user,
            )
        
        category_mapping[main_category_name.lower()] = main_category
        
        # Create subcategories
        for subcategory_name in subcategories:
            # Find existing subcategory
            existing_subcategory = Subcategory.objects.filter(
                category=main_category,
                name__iexact=subcategory_name
            ).first()
            if existing_subcategory:
                subcategory = existing_subcategory
            else:
                # Create new subcategory
                first_user = apps.get_model('auth', 'User').objects.first()
                if not first_user:
                    continue
                subcategory = Subcategory.objects.create(
                    category=main_category,
                    name=subcategory_name,
                    user=first_user,
                )
            
            subcategory_mapping[(main_category_name.lower(), subcategory_name.lower())] = subcategory
    
    # Update existing expenses to use global categories
    for expense in Expense.objects.all():
        if expense.category:
            category_name = expense.category.name.lower()
            if category_name in category_mapping:
                expense.category = category_mapping[category_name]
            
            if expense.subcategory:
                subcategory_name = expense.subcategory.name.lower()
                key = (category_name, subcategory_name)
                if key in subcategory_mapping:
                    expense.subcategory = subcategory_mapping[key]
            
            expense.save()
    
    # Delete duplicate categories (keep one of each name)
    seen_names = set()
    for category in Category.objects.all():
        name_lower = category.name.lower()
        if name_lower in seen_names:
            # This is a duplicate, delete it (but only if no expenses reference it)
            if not Expense.objects.filter(category=category).exists():
                category.delete()
        else:
            seen_names.add(name_lower)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_expense_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_to_global_categories),
    ]
