# Generated by Django 4.2.27 on 2026-01-25 12:45

from django.db import migrations
from django.conf import settings
import os


def create_google_social_app(apps, schema_editor):
    """Create Google social application for allauth."""
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    Site = apps.get_model('sites', 'Site')
    
    # Get the site
    try:
        site = Site.objects.get(pk=settings.SITE_ID)
    except Site.DoesNotExist:
        site = Site.objects.get_or_create(
            pk=settings.SITE_ID,
            defaults={'domain': 'localhost:8000', 'name': 'localhost'}
        )[0]
    
    # Get Google credentials from settings
    client_id = getattr(settings, 'GOOGLE_CLIENT_ID', '')
    client_secret = getattr(settings, 'GOOGLE_CLIENT_SECRET', '')
    
    if client_id and client_secret:
        # Create or update Google social app
        social_app, created = SocialApp.objects.get_or_create(
            provider='google',
            defaults={
                'name': 'Google',
                'client_id': client_id,
                'secret': client_secret,
            }
        )
        
        if not social_app.sites.filter(pk=site.pk).exists():
            social_app.sites.add(site)
        
        if created:
            print("Created Google social application")
        else:
            print("Updated Google social application")


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_remove_user_fields'),
        ('socialaccount', '0001_initial'),  # Ensure socialaccount tables exist
        ('sites', '0001_initial'),  # Ensure sites table exists
    ]

    operations = [
        migrations.RunPython(create_google_social_app),
    ]